### ISSUE TITLE
modify the resolution manually

### ISSUE THREAD

**Issue by GuoqiangW** [openFyde/overlay-rock5b-openfyde#12]
I have a 2560*1660 portable screen, but it can only output 1920*1080, can it be modified manually? the image used is rock5b-openfyde-r108.img.xz

**Comment by DarkevilPT** [comment]
I have a story to tell about this.
My screen resolution is also 2560x1660p.
However last week for some reason It was only detecting 1920x1080p.
No on OpenFyde I couldnt do nothing. But on the screen settings I noticed I had HDR turned on and there was some other option that couldnt the screen trigger the 120hz something HCP. 
In Short I have a 2k screen that can do 120hz however thats not the case if connected via hdmi only via type c.
So it does 2k@60hz but there was an option it that was preventing openFyde from pulling its max resolution.
My suggestions... try playing with it HDR etc

**Comment by Damenly** [comment]
Via HDMI or Type-C?

**Comment by DarkevilPT** [comment]
> Via HDMI or Type-C?

My case Hdmi as type C is connected to an HUB.

**Comment by DarkevilPT** [comment]
![20230321_203040](https://user-images.githubusercontent.com/3583885/226733491-d906633a-bd71-4e38-a441-adc277619141.jpg)
On mine if I turn off freesync and then reboot sometimes puts my screen locked to 1080p.
The way to fix it is to turn it on. This is an issue that only happened to me once.

**Comment by GuoqiangW** [comment]
my screen only has HDMI, no HDR no sync, i tried many times, only 1080p can be detected

**Comment by Damenly** [comment]
> my screen only has HDMI, no HDR no sync, i tried many times, only 1080p can be detected

OK. May I know your monitor model?

**Comment by GuoqiangW** [comment]
> > my screen only has HDMI, no HDR no sync, i tried many times, only 1080p can be detected
> 
> OK. May I know your monitor model?

VFV16in, display driver board is rtd2555T or rtd2556T? panel is NE160QDM-NY3
I‘ve tried armbian and another rk3399 board, it worked well
