### ISSUE TITLE
remote desktop error

### ISSUE THREAD

**Issue by flymzero** [openFyde/overlay-rock5b-openfyde#14]
use https://rdp.fydeos.com show some error
<img width="436" alt="image" src="https://user-images.githubusercontent.com/13290769/229298547-eb6792d8-a6e8-4d1d-a324-c2546801e85b.png">

**Comment by Damenly** [comment]
openfyde doesn't support [rdp.fydeos.com](https://rdp.fydeos.com/) for now.
