### ISSUE TITLE
R114 - Problems

### ISSUE THREAD

**Issue by DarkevilPT** [openFyde/overlay-rock5b-openfyde#23]
Rock 5B on 114 Issues:

1 - Hours Time (For some reason the time is not being updated as it should).

<s>2 - Android container - Super glitchy bugged to say the least apkpure keeps 'crashing' a bit inconsistent.
[Screen_recording_2023-07-15_06.16.29.webm](https://github.com/openFyde/overlay-rock5b-openfyde/assets/3583885/0bf90811-edf8-4d35-87fb-e59e0607cde1)
![image](https://github.com/openFyde/overlay-rock5b-openfyde/assets/3583885/84145963-f878-45cb-88bb-80512c3e61dd)</s> **Partially fixed** works fine just has a windowing issue but resizing it fixes.

3 - Steam apparently the same tutorial doesn't seems to be working on my side. 

<s>4 - Linux container - Slow super slow doing tasks.. some what buggy.</s> **Fixed**
<s>5 - Widevine done by the book but... not working on me?
[Screen recording 2023-07-15 07.20.03.webm](https://github.com/openFyde/overlay-rock5b-openfyde/assets/3583885/4d76c2e8-752c-4aeb-ad78-48c2c859c558)
(Also geforce now with widevine on still doesn't recognizes Chromium browser as an supported browser).</s> **Fixed and with Lacros it works too**

**Comment by Damenly** [comment]
Thanks for you detailed issues.

1. Our service is broken down. Will be fixed.
2. Yeah. BUG. Regression.
3 & 4. From r114, box64 support will be removed from openFyde. Sorry, it's not mentioned in the changelog.
Linux container will be origin as chromiumOS. 
5. Widevine is for Chromium of host not Android. Try Netflix/Spotify/DRM content in webpages.

**Comment by DarkevilPT** [comment]
> 4. (Actually 5, blame Markdown) Widevine is for Chromium of host not Android. Try Netflix/Spotify/DRM content in webpages.

That video I took is on the Chromium browser not Android.
It just looks like that due to the Page Shortcut.

--

5 - If yous manage to fix the user agents please let me know cause that interests me.

**Comment by Damenly** [comment]
Oh. I see. I tested Spofiy only. Netflix and Gforce issues are both caused by the user agent. Once it's fixed we will 
release a new version since it counts.

**Comment by DarkevilPT** [comment]
> Oh. I see. I tested Spotify only. Netflix and Gforce issues are both caused by the user agent. Once it's fixed we will release a new version since it counts.

Hey man thank you a million!

**Comment by DarkevilPT** [comment]
Hours are fixed.
No steam but things seems to be fine.
