### ISSUE TITLE
How to install Google Apps or Apks?

### ISSUE THREAD

**Issue by DarkevilPT** [openFyde/overlay-rock5b-openfyde#3]
Hi OpenFyde OS,
When will we be able to install OpenFyde gApps.

Or can we install them via linux command lines or any other way?

**Comment by DarkevilPT** [comment]
Also @Damenly when will I be able to connect my bluetooth speaker to Open Fyde as A8 Bluetooth module is still not working properly..

**Comment by Damenly** [comment]
As we discussed before, it needs time. Im working on preparing works of it. Thanks
