### ISSUE TITLE
Nvme boot support?

### ISSUE THREAD

**Issue by Funarp** [openFyde/overlay-rock5b-openfyde#4]
Can I install openfyde into nvme and boot from it?

**Comment by Damenly** [comment]
Yes. Please refer to the steps in release note. Thanks .

**Comment by Funarp** [comment]
thanks for reply, but i don't know how to use [upgrade_tool](https://github.com/openFyde/chromium_os-rk3588/tree/r102-dev/rk3588-image-maker/Linux_Upgrade_Tool) to flash into NVME

**Comment by Damenly** [comment]
The new release now supports NVME installation.

**Comment by Funarp** [comment]
Thank you for telling me, I'll try it!
