### ISSUE TITLE
AP6256 network module does not work

### ISSUE THREAD

**Issue by yuta-sakata** [openFyde/overlay-rock5b-openfyde#5]
After I installed Openfyde, I could not connect to WIFI, resulting in my inability to perform initialization and networking. The model of the network module inserted on the board is AP6256

**Comment by Damenly** [comment]
Thanks for the report. Try to fix it in next release.

**Comment by yuta-sakata** [comment]
BUG复现了，这次是能搜索到网络但是无法联网

**Comment by DarkevilPT** [comment]
AX210 AX200 AC8265 Wireless Module for Laptop M.2 NGFF
https://a.aliexpress.com/_mKCUTTs
