### ISSUE TITLE
3 Bluetooth Devices and .. bad issues start to happen.

### ISSUE THREAD

**Issue by DarkevilPT** [openFyde/overlay-rock5b-openfyde#6]
Specially if one BT is for Audio..
I got my bt keyboard working no issues, my JBL BT Speaker plays audio first than youtube plays video.
Then I decided to add my BT Controller for some genshin impact try and puff my audio just goes cracking wont work well.

https://youtu.be/acFHAO7aMoM

**Comment by Damenly** [comment]
How is it going if three devices are connected but no android app running?

**Comment by DarkevilPT** [comment]
> How is it going if three devices are connected but no android app running?

Just tried again and without android apps running same happens I mean.. they werent even before..
Its hard to understand if its my speaker or my controller that makes this happen.. either way I dont have with me a best suitable fourth option to remove the controller out of the picture to see which one makes it happen..
The speaker sound 'craps' it self and forgetting the controller the only way to fix the audio is by forgetting the JBL 5 Speaker and synchronizing it again.

It's a bit ackward but theres something there. 
https://www.youtube.com/shorts/ZJC7jiz_mus

**Comment by DarkevilPT** [comment]
Ok so: 
Bluetooth controllers or wired controllers don't work at all.
Bluetooth controllers while JBL Speaker 5 is playing music it just screws up the connection and starts gagging.
--
From a close friend who was the AX210 module he can't use it on openFyde so he went back to his wifi bt dongle and it also doesn't work despite being shown on usb gadgets on openFyde just nothing for wifi networks or bluetooth scan.

**Comment by DarkevilPT** [comment]
@Damenly Found this about bluetooth working on The Android container (hopefully it helps on the openFyde gamepad bluetooth support too) (I havent tested it yet).

```
#how to use bluetooth in Android container in docker with ax210
this is my command
docker run -itd --privileged
–pull always
-v “$(pwd)”/Android:/data
-v /dev:/dev
-v /run/dbus:/run/dbus
-v /var/run/dbus:/var/run/dbus
–mount=type=bind,source=/dev/mali0,destination=/dev/mali0
-p 5555:5555
chisbread/rk3588-gaming:redroid-firefly
androidboot.redroid_width=1080
androidboot.redroid_height=1920
androidboot.redroid_dpi=480
androidboot.redroid_fps=30
androidboot.redroid_gpu_mode=host
my Bluetooth device
Bus 001 Device 004: ID 8087:0032 Intel Corp. AX210 Bluetooth
```

**Comment by Damenly** [comment]
> @Damenly Found this about bluetooth working on The Android container (hopefully it helps on the openFyde gamepad bluetooth support too) (I havent tested it yet).
> 
> ```
> #how to use bluetooth in Android container in docker with ax210
> this is my command
> docker run -itd --privileged
> –pull always
> -v “$(pwd)”/Android:/data
> -v /dev:/dev
> -v /run/dbus:/run/dbus
> -v /var/run/dbus:/var/run/dbus
> –mount=type=bind,source=/dev/mali0,destination=/dev/mali0
> -p 5555:5555
> chisbread/rk3588-gaming:redroid-firefly
> androidboot.redroid_width=1080
> androidboot.redroid_height=1920
> androidboot.redroid_dpi=480
> androidboot.redroid_fps=30
> androidboot.redroid_gpu_mode=host
> my Bluetooth device
> Bus 001 Device 004: ID 8087:0032 Intel Corp. AX210 Bluetooth
> ```

Container things. Thanks. learned it!

**Comment by DarkevilPT** [comment]
Apparently I cant have more than one device using 2.4Ghz BT at the same time with wifi on 2.4Ghz connection.
If I use Wifi 5Ghz and then connect an audio Speaker to BT (which is 2.4) I get no problems at all. 
There is this issue apparently.

**Comment by Damenly** [comment]
2.4Ghz BT and Wifi interference is a well-known phenomenon that occurs on many devices(Apple included).
So I'd say that we can't do more at this moment. Or does it happen in openfyde only?

**Comment by DarkevilPT** [comment]
> 2.4Ghz BT and Wifi interference is a well-known phenomenon that occurs on many devices(Apple included). So I'd say that we can't do more at this moment. Or does it happen in openfyde only?

on Armbian I dont have that issue apparently.
I can have audio JBL speaker working plus gamepad plus keyboard.
Wifi I dont remember for sure I think i always used 5Ghz.

**Comment by DarkevilPT** [comment]
Update: On FydeOS for You the 3 Bluetooth devices all connected wont interfere with the JBL 5 Speaker I'm talking about the usage on the AX210 module. Works like a Charm I haven't just however tried the with also the Wifi 2.4Ghz connect plus all 3 bluetooth devices.
