### ISSUE TITLE
Fan Control Enhancement

### ISSUE THREAD

**Issue by DarkevilPT** [openFyde/overlay-rock5b-openfyde#8]
Lukasz made a better fan control for best behaviour and less noise non-stop and to be honest I think this is simply the most balanced between fast noisy and a slow barely lowering down cpu temperatures etc.. so this is just a 'final' suggestion for a fan enhancement if I still may.

```
git clone https://github.com/lukaszsobala/fan-control-rock5b
cd fan-control-rock5b
make package
sudo dpkg -i fan-control*.deb
sudo systemctl enable fan-control
systemctl start fan-control
```

**Comment by DarkevilPT** [comment]
I really have to ask you... this Lukasz config file is much better than the previous pymumu one if you could on a next version release this one.. I would have us all much happier. 
We have came from 8 slow to 80 ultra fast.. Middle term pleasee!!

**Comment by Damenly** [comment]
I'm doing preparations for the next release and realized there's no other difference but only `etc/fan-control.json`.
Please replace the file with `https://raw.githubusercontent.com/lukaszsobala/fan-control-rock5b/main/etc/fan-control.json`.
For me, the strategy of lukaszsobala makes fan annoying.

**Comment by DarkevilPT** [comment]
Ok just go with the flow.. whatever that works best for me is fine.

**Comment by DarkevilPT** [comment]
I dont know what version of the file armbian is using at the moment but their fan behaviour is just the best.
If I found out I will share it.

**Comment by DarkevilPT** [comment]
> I'm doing preparations for the next release and realized there's no other difference but only `etc/fan-control.json`. Please replace the file with `https://raw.githubusercontent.com/lukaszsobala/fan-control-rock5b/main/etc/fan-control.json`. For me, the strategy of lukaszsobala makes fan annoying.

Do you use the oficial radxa fan?

**Comment by DarkevilPT** [comment]
Here is is Damenly: https://forum.radxa.com/t/time-to-get-rid-of-these-userspace-pwm-fan-controll-shit/15077

Please use this config file as it is perfect !
